# Generated by Django 4.2.2 on 2023-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("stars", models.IntegerField()),
            ],
        ),
    ]
